/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 65
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_whitespaces = 1,
  sym_new_lines = 2,
  sym_comment_content = 3,
  anon_sym_POUND = 4,
  anon_sym_POUND_POUND = 5,
  anon_sym_POUND_POUND_POUND = 6,
  anon_sym_LF = 7,
  sym_prec_whitespaces = 8,
  sym__identifier = 9,
  anon_sym_DASH = 10,
  sym_assignment = 11,
  sym_text = 12,
  aux_sym_message_continuation_token1 = 13,
  anon_sym_LBRACE = 14,
  anon_sym_RBRACE = 15,
  anon_sym_DQUOTE = 16,
  aux_sym_quoted_text_token1 = 17,
  anon_sym_BSLASHu = 18,
  anon_sym_BSLASHU = 19,
  anon_sym_BSLASH_DQUOTE = 20,
  anon_sym_BSLASH_BSLASH = 21,
  sym__hexdigit = 22,
  sym_source = 23,
  sym_blank_lines = 24,
  sym_comment = 25,
  sym_group_comment = 26,
  sym_file_comment = 27,
  sym_message_with_comment = 28,
  sym_message = 29,
  sym_identifier = 30,
  sym_term = 31,
  sym_message_value = 32,
  sym_pattern = 33,
  sym_message_continuation = 34,
  sym_placeable = 35,
  sym_quoted_text = 36,
  sym_quoted_escaped = 37,
  aux_sym_source_repeat1 = 38,
  aux_sym_blank_lines_repeat1 = 39,
  aux_sym_message_with_comment_repeat1 = 40,
  aux_sym_message_value_repeat1 = 41,
  aux_sym_pattern_repeat1 = 42,
  aux_sym_quoted_text_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_whitespaces] = "whitespaces",
  [sym_new_lines] = "new_lines",
  [sym_comment_content] = "comment_content",
  [anon_sym_POUND] = "#",
  [anon_sym_POUND_POUND] = "##",
  [anon_sym_POUND_POUND_POUND] = "###",
  [anon_sym_LF] = "\n",
  [sym_prec_whitespaces] = "prec_whitespaces",
  [sym__identifier] = "_identifier",
  [anon_sym_DASH] = "-",
  [sym_assignment] = "assignment",
  [sym_text] = "text",
  [aux_sym_message_continuation_token1] = "message_continuation_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_text_token1] = "quoted_text_token1",
  [anon_sym_BSLASHu] = "\\u",
  [anon_sym_BSLASHU] = "\\U",
  [anon_sym_BSLASH_DQUOTE] = "\\\"",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [sym__hexdigit] = "_hexdigit",
  [sym_source] = "source",
  [sym_blank_lines] = "blank_lines",
  [sym_comment] = "comment",
  [sym_group_comment] = "group_comment",
  [sym_file_comment] = "file_comment",
  [sym_message_with_comment] = "message_with_comment",
  [sym_message] = "message",
  [sym_identifier] = "identifier",
  [sym_term] = "term",
  [sym_message_value] = "message_value",
  [sym_pattern] = "pattern",
  [sym_message_continuation] = "message_continuation",
  [sym_placeable] = "placeable",
  [sym_quoted_text] = "quoted_text",
  [sym_quoted_escaped] = "quoted_escaped",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_blank_lines_repeat1] = "blank_lines_repeat1",
  [aux_sym_message_with_comment_repeat1] = "message_with_comment_repeat1",
  [aux_sym_message_value_repeat1] = "message_value_repeat1",
  [aux_sym_pattern_repeat1] = "pattern_repeat1",
  [aux_sym_quoted_text_repeat1] = "quoted_text_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_whitespaces] = sym_whitespaces,
  [sym_new_lines] = sym_new_lines,
  [sym_comment_content] = sym_comment_content,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_POUND_POUND] = anon_sym_POUND_POUND,
  [anon_sym_POUND_POUND_POUND] = anon_sym_POUND_POUND_POUND,
  [anon_sym_LF] = anon_sym_LF,
  [sym_prec_whitespaces] = sym_prec_whitespaces,
  [sym__identifier] = sym__identifier,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_assignment] = sym_assignment,
  [sym_text] = sym_text,
  [aux_sym_message_continuation_token1] = aux_sym_message_continuation_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_text_token1] = aux_sym_quoted_text_token1,
  [anon_sym_BSLASHu] = anon_sym_BSLASHu,
  [anon_sym_BSLASHU] = anon_sym_BSLASHU,
  [anon_sym_BSLASH_DQUOTE] = anon_sym_BSLASH_DQUOTE,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [sym__hexdigit] = sym__hexdigit,
  [sym_source] = sym_source,
  [sym_blank_lines] = sym_blank_lines,
  [sym_comment] = sym_comment,
  [sym_group_comment] = sym_group_comment,
  [sym_file_comment] = sym_file_comment,
  [sym_message_with_comment] = sym_message_with_comment,
  [sym_message] = sym_message,
  [sym_identifier] = sym_identifier,
  [sym_term] = sym_term,
  [sym_message_value] = sym_message_value,
  [sym_pattern] = sym_pattern,
  [sym_message_continuation] = sym_message_continuation,
  [sym_placeable] = sym_placeable,
  [sym_quoted_text] = sym_quoted_text,
  [sym_quoted_escaped] = sym_quoted_escaped,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_blank_lines_repeat1] = aux_sym_blank_lines_repeat1,
  [aux_sym_message_with_comment_repeat1] = aux_sym_message_with_comment_repeat1,
  [aux_sym_message_value_repeat1] = aux_sym_message_value_repeat1,
  [aux_sym_pattern_repeat1] = aux_sym_pattern_repeat1,
  [aux_sym_quoted_text_repeat1] = aux_sym_quoted_text_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_whitespaces] = {
    .visible = true,
    .named = true,
  },
  [sym_new_lines] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_prec_whitespaces] = {
    .visible = true,
    .named = true,
  },
  [sym__identifier] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_message_continuation_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_text_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASHu] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHU] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [sym__hexdigit] = {
    .visible = false,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym_blank_lines] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_group_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_file_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_message_with_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_message] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_message_value] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_message_continuation] = {
    .visible = true,
    .named = true,
  },
  [sym_placeable] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_text] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_escaped] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_blank_lines_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_message_with_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_message_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_text_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '\n', 22,
        '"', 32,
        '#', 29,
        '-', 32,
        '=', 32,
        '\\', 27,
        '{', 34,
        '}', 35,
        '\t', 23,
        ' ', 23,
      );
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F')) ADVANCE(32);
      if (lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '{') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(32);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(36);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == 'U') ADVANCE(39);
      if (lookahead == '\\') ADVANCE(41);
      if (lookahead == 'u') ADVANCE(38);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == '-') ADVANCE(25);
      if (lookahead == '=') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 5:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(33);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(42);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 8:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '\n', 14,
        '"', 36,
        '#', 18,
        '-', 25,
        '=', 26,
        '}', 35,
        '\t', 13,
        ' ', 13,
      );
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 9:
      if (eof) ADVANCE(12);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '#') ADVANCE(29);
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == '{') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(32);
      END_STATE();
    case 10:
      if (eof) ADVANCE(12);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '-') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '\n') ADVANCE(21);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '-') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_whitespaces);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_new_lines);
      if (lookahead == '\n') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_new_lines);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(33);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '#') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_POUND_POUND);
      if (lookahead == '#') ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(14);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(33);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_prec_whitespaces);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_assignment);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '"') ADVANCE(32);
      if (lookahead == 'U') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(32);
      if (lookahead == 'u') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(32);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '#') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(32);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(32);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_message_continuation_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_quoted_text_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_BSLASHu);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_BSLASHU);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_BSLASH_DQUOTE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__hexdigit);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 9},
  [5] = {.lex_state = 9},
  [6] = {.lex_state = 10},
  [7] = {.lex_state = 10},
  [8] = {.lex_state = 9},
  [9] = {.lex_state = 10},
  [10] = {.lex_state = 9},
  [11] = {.lex_state = 9},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 11},
  [14] = {.lex_state = 11},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 8},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 8},
  [20] = {.lex_state = 8},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 9},
  [24] = {.lex_state = 8},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 9},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 9},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 8},
  [38] = {.lex_state = 8},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 8},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 8},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 6},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 8},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 7},
  [52] = {.lex_state = 6},
  [53] = {.lex_state = 6},
  [54] = {.lex_state = 7},
  [55] = {.lex_state = 7},
  [56] = {.lex_state = 6},
  [57] = {.lex_state = 6},
  [58] = {.lex_state = 6},
  [59] = {.lex_state = 6},
  [60] = {.lex_state = 6},
  [61] = {.lex_state = 6},
  [62] = {.lex_state = 6},
  [63] = {.lex_state = 11},
  [64] = {.lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_whitespaces] = ACTIONS(1),
    [sym_new_lines] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym_prec_whitespaces] = ACTIONS(1),
    [sym__identifier] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_assignment] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
    [aux_sym_message_continuation_token1] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASHu] = ACTIONS(1),
    [anon_sym_BSLASHU] = ACTIONS(1),
    [anon_sym_BSLASH_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(1),
    [sym__hexdigit] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source] = STATE(48),
    [sym_blank_lines] = STATE(2),
    [sym_comment] = STATE(13),
    [sym_group_comment] = STATE(2),
    [sym_file_comment] = STATE(2),
    [sym_message_with_comment] = STATE(2),
    [sym_message] = STATE(2),
    [sym_identifier] = STATE(39),
    [sym_term] = STATE(39),
    [aux_sym_source_repeat1] = STATE(2),
    [aux_sym_blank_lines_repeat1] = STATE(12),
    [aux_sym_message_with_comment_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_whitespaces] = ACTIONS(5),
    [sym_new_lines] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_POUND_POUND] = ACTIONS(9),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(11),
    [sym__identifier] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_POUND_POUND,
    ACTIONS(11), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(12), 1,
      aux_sym_blank_lines_repeat1,
    STATE(13), 1,
      sym_comment,
    STATE(21), 1,
      aux_sym_message_with_comment_repeat1,
    ACTIONS(5), 2,
      sym_whitespaces,
      sym_new_lines,
    STATE(39), 2,
      sym_identifier,
      sym_term,
    STATE(3), 6,
      sym_blank_lines,
      sym_group_comment,
      sym_file_comment,
      sym_message_with_comment,
      sym_message,
      aux_sym_source_repeat1,
  [44] = 12,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(24), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      anon_sym_POUND_POUND,
    ACTIONS(30), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(36), 1,
      anon_sym_DASH,
    STATE(12), 1,
      aux_sym_blank_lines_repeat1,
    STATE(13), 1,
      sym_comment,
    STATE(21), 1,
      aux_sym_message_with_comment_repeat1,
    ACTIONS(21), 2,
      sym_whitespaces,
      sym_new_lines,
    STATE(39), 2,
      sym_identifier,
      sym_term,
    STATE(3), 6,
      sym_blank_lines,
      sym_group_comment,
      sym_file_comment,
      sym_message_with_comment,
      sym_message,
      aux_sym_source_repeat1,
  [88] = 5,
    ACTIONS(43), 1,
      sym_text,
    ACTIONS(46), 1,
      anon_sym_LBRACE,
    ACTIONS(39), 2,
      ts_builtin_sym_end,
      aux_sym_message_continuation_token1,
    STATE(4), 2,
      sym_placeable,
      aux_sym_pattern_repeat1,
    ACTIONS(41), 7,
      sym_whitespaces,
      sym_new_lines,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      sym__identifier,
      anon_sym_DASH,
  [112] = 5,
    ACTIONS(53), 1,
      sym_text,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 2,
      ts_builtin_sym_end,
      aux_sym_message_continuation_token1,
    STATE(4), 2,
      sym_placeable,
      aux_sym_pattern_repeat1,
    ACTIONS(51), 7,
      sym_whitespaces,
      sym_new_lines,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      sym__identifier,
      anon_sym_DASH,
  [136] = 4,
    ACTIONS(61), 1,
      aux_sym_message_continuation_token1,
    STATE(7), 2,
      sym_message_continuation,
      aux_sym_message_value_repeat1,
    ACTIONS(59), 3,
      sym_new_lines,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
    ACTIONS(57), 5,
      ts_builtin_sym_end,
      sym_whitespaces,
      anon_sym_POUND_POUND_POUND,
      sym__identifier,
      anon_sym_DASH,
  [156] = 4,
    ACTIONS(61), 1,
      aux_sym_message_continuation_token1,
    STATE(9), 2,
      sym_message_continuation,
      aux_sym_message_value_repeat1,
    ACTIONS(65), 3,
      sym_new_lines,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
    ACTIONS(63), 5,
      ts_builtin_sym_end,
      sym_whitespaces,
      anon_sym_POUND_POUND_POUND,
      sym__identifier,
      anon_sym_DASH,
  [176] = 2,
    ACTIONS(67), 4,
      ts_builtin_sym_end,
      sym_text,
      aux_sym_message_continuation_token1,
      anon_sym_LBRACE,
    ACTIONS(69), 7,
      sym_whitespaces,
      sym_new_lines,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      sym__identifier,
      anon_sym_DASH,
  [192] = 4,
    ACTIONS(75), 1,
      aux_sym_message_continuation_token1,
    STATE(9), 2,
      sym_message_continuation,
      aux_sym_message_value_repeat1,
    ACTIONS(73), 3,
      sym_new_lines,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
    ACTIONS(71), 5,
      ts_builtin_sym_end,
      sym_whitespaces,
      anon_sym_POUND_POUND_POUND,
      sym__identifier,
      anon_sym_DASH,
  [212] = 2,
    ACTIONS(78), 4,
      ts_builtin_sym_end,
      sym_text,
      aux_sym_message_continuation_token1,
      anon_sym_LBRACE,
    ACTIONS(80), 7,
      sym_whitespaces,
      sym_new_lines,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      sym__identifier,
      anon_sym_DASH,
  [228] = 2,
    ACTIONS(82), 4,
      ts_builtin_sym_end,
      sym_text,
      aux_sym_message_continuation_token1,
      anon_sym_LBRACE,
    ACTIONS(84), 7,
      sym_whitespaces,
      sym_new_lines,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      sym__identifier,
      anon_sym_DASH,
  [244] = 4,
    STATE(17), 1,
      aux_sym_blank_lines_repeat1,
    ACTIONS(88), 2,
      sym_whitespaces,
      sym_new_lines,
    ACTIONS(90), 2,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
    ACTIONS(86), 4,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND,
      sym__identifier,
      anon_sym_DASH,
  [262] = 3,
    ACTIONS(96), 1,
      anon_sym_LF,
    ACTIONS(94), 3,
      sym_new_lines,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
    ACTIONS(92), 5,
      ts_builtin_sym_end,
      sym_whitespaces,
      anon_sym_POUND_POUND_POUND,
      sym__identifier,
      anon_sym_DASH,
  [278] = 2,
    ACTIONS(100), 4,
      sym_new_lines,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_LF,
    ACTIONS(98), 5,
      ts_builtin_sym_end,
      sym_whitespaces,
      anon_sym_POUND_POUND_POUND,
      sym__identifier,
      anon_sym_DASH,
  [292] = 7,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      aux_sym_message_continuation_token1,
    ACTIONS(102), 1,
      sym_prec_whitespaces,
    ACTIONS(104), 1,
      sym_text,
    STATE(25), 1,
      sym_message_value,
    STATE(5), 2,
      sym_placeable,
      aux_sym_pattern_repeat1,
    STATE(6), 2,
      sym_pattern,
      sym_message_continuation,
  [316] = 7,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      aux_sym_message_continuation_token1,
    ACTIONS(104), 1,
      sym_text,
    ACTIONS(106), 1,
      sym_prec_whitespaces,
    STATE(24), 1,
      sym_message_value,
    STATE(5), 2,
      sym_placeable,
      aux_sym_pattern_repeat1,
    STATE(6), 2,
      sym_pattern,
      sym_message_continuation,
  [340] = 4,
    STATE(17), 1,
      aux_sym_blank_lines_repeat1,
    ACTIONS(110), 2,
      sym_whitespaces,
      sym_new_lines,
    ACTIONS(113), 2,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
    ACTIONS(108), 4,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND,
      sym__identifier,
      anon_sym_DASH,
  [358] = 2,
    ACTIONS(117), 3,
      sym_new_lines,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
    ACTIONS(115), 6,
      ts_builtin_sym_end,
      sym_whitespaces,
      anon_sym_POUND_POUND_POUND,
      sym__identifier,
      anon_sym_DASH,
      aux_sym_message_continuation_token1,
  [372] = 2,
    ACTIONS(121), 2,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
    ACTIONS(119), 6,
      ts_builtin_sym_end,
      sym_whitespaces,
      sym_new_lines,
      anon_sym_POUND_POUND_POUND,
      sym__identifier,
      anon_sym_DASH,
  [385] = 2,
    ACTIONS(125), 2,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
    ACTIONS(123), 6,
      ts_builtin_sym_end,
      sym_whitespaces,
      sym_new_lines,
      anon_sym_POUND_POUND_POUND,
      sym__identifier,
      anon_sym_DASH,
  [398] = 7,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(127), 1,
      anon_sym_POUND,
    STATE(22), 1,
      sym_message,
    STATE(34), 1,
      aux_sym_message_with_comment_repeat1,
    STATE(63), 1,
      sym_comment,
    STATE(39), 2,
      sym_identifier,
      sym_term,
  [421] = 2,
    ACTIONS(131), 2,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
    ACTIONS(129), 6,
      ts_builtin_sym_end,
      sym_whitespaces,
      sym_new_lines,
      anon_sym_POUND_POUND_POUND,
      sym__identifier,
      anon_sym_DASH,
  [434] = 6,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      aux_sym_message_continuation_token1,
    ACTIONS(133), 1,
      sym_text,
    STATE(25), 1,
      sym_message_value,
    STATE(5), 2,
      sym_placeable,
      aux_sym_pattern_repeat1,
    STATE(6), 2,
      sym_pattern,
      sym_message_continuation,
  [455] = 2,
    ACTIONS(137), 2,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
    ACTIONS(135), 6,
      ts_builtin_sym_end,
      sym_whitespaces,
      sym_new_lines,
      anon_sym_POUND_POUND_POUND,
      sym__identifier,
      anon_sym_DASH,
  [468] = 2,
    ACTIONS(141), 2,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
    ACTIONS(139), 6,
      ts_builtin_sym_end,
      sym_whitespaces,
      sym_new_lines,
      anon_sym_POUND_POUND_POUND,
      sym__identifier,
      anon_sym_DASH,
  [481] = 6,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      aux_sym_message_continuation_token1,
    ACTIONS(133), 1,
      sym_text,
    STATE(28), 1,
      sym_message_value,
    STATE(5), 2,
      sym_placeable,
      aux_sym_pattern_repeat1,
    STATE(6), 2,
      sym_pattern,
      sym_message_continuation,
  [502] = 6,
    ACTIONS(143), 1,
      anon_sym_DQUOTE,
    ACTIONS(145), 1,
      aux_sym_quoted_text_token1,
    ACTIONS(147), 1,
      anon_sym_BSLASHu,
    ACTIONS(149), 1,
      anon_sym_BSLASHU,
    ACTIONS(151), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(30), 2,
      sym_quoted_escaped,
      aux_sym_quoted_text_repeat1,
  [523] = 2,
    ACTIONS(155), 2,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
    ACTIONS(153), 6,
      ts_builtin_sym_end,
      sym_whitespaces,
      sym_new_lines,
      anon_sym_POUND_POUND_POUND,
      sym__identifier,
      anon_sym_DASH,
  [536] = 6,
    ACTIONS(147), 1,
      anon_sym_BSLASHu,
    ACTIONS(149), 1,
      anon_sym_BSLASHU,
    ACTIONS(157), 1,
      anon_sym_DQUOTE,
    ACTIONS(159), 1,
      aux_sym_quoted_text_token1,
    ACTIONS(151), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(27), 2,
      sym_quoted_escaped,
      aux_sym_quoted_text_repeat1,
  [557] = 6,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    ACTIONS(163), 1,
      aux_sym_quoted_text_token1,
    ACTIONS(166), 1,
      anon_sym_BSLASHu,
    ACTIONS(169), 1,
      anon_sym_BSLASHU,
    ACTIONS(172), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(30), 2,
      sym_quoted_escaped,
      aux_sym_quoted_text_repeat1,
  [578] = 1,
    ACTIONS(175), 6,
      anon_sym_DQUOTE,
      aux_sym_quoted_text_token1,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
  [587] = 1,
    ACTIONS(177), 6,
      anon_sym_DQUOTE,
      aux_sym_quoted_text_token1,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
  [596] = 1,
    ACTIONS(179), 6,
      anon_sym_DQUOTE,
      aux_sym_quoted_text_token1,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
  [605] = 4,
    ACTIONS(181), 1,
      anon_sym_POUND,
    STATE(34), 1,
      aux_sym_message_with_comment_repeat1,
    STATE(63), 1,
      sym_comment,
    ACTIONS(184), 2,
      sym__identifier,
      anon_sym_DASH,
  [619] = 4,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(133), 1,
      sym_text,
    STATE(18), 1,
      sym_pattern,
    STATE(5), 2,
      sym_placeable,
      aux_sym_pattern_repeat1,
  [633] = 1,
    ACTIONS(184), 3,
      anon_sym_POUND,
      sym__identifier,
      anon_sym_DASH,
  [639] = 3,
    ACTIONS(186), 1,
      sym_whitespaces,
    ACTIONS(188), 1,
      anon_sym_DQUOTE,
    STATE(40), 1,
      sym_quoted_text,
  [649] = 2,
    ACTIONS(190), 1,
      sym_whitespaces,
    ACTIONS(192), 1,
      anon_sym_RBRACE,
  [656] = 2,
    ACTIONS(194), 1,
      sym_prec_whitespaces,
    ACTIONS(196), 1,
      sym_assignment,
  [663] = 2,
    ACTIONS(198), 1,
      sym_whitespaces,
    ACTIONS(200), 1,
      anon_sym_RBRACE,
  [670] = 1,
    ACTIONS(202), 2,
      sym_whitespaces,
      anon_sym_RBRACE,
  [675] = 1,
    ACTIONS(204), 2,
      sym_whitespaces,
      anon_sym_RBRACE,
  [680] = 1,
    ACTIONS(206), 2,
      sym_prec_whitespaces,
      sym_assignment,
  [685] = 2,
    ACTIONS(188), 1,
      anon_sym_DQUOTE,
    STATE(38), 1,
      sym_quoted_text,
  [692] = 1,
    ACTIONS(208), 2,
      sym_prec_whitespaces,
      sym_assignment,
  [697] = 1,
    ACTIONS(210), 1,
      sym__hexdigit,
  [701] = 1,
    ACTIONS(192), 1,
      anon_sym_RBRACE,
  [705] = 1,
    ACTIONS(212), 1,
      ts_builtin_sym_end,
  [709] = 1,
    ACTIONS(214), 1,
      sym_assignment,
  [713] = 1,
    ACTIONS(216), 1,
      anon_sym_RBRACE,
  [717] = 1,
    ACTIONS(218), 1,
      sym_comment_content,
  [721] = 1,
    ACTIONS(220), 1,
      sym__hexdigit,
  [725] = 1,
    ACTIONS(222), 1,
      sym__hexdigit,
  [729] = 1,
    ACTIONS(224), 1,
      sym_comment_content,
  [733] = 1,
    ACTIONS(226), 1,
      sym_comment_content,
  [737] = 1,
    ACTIONS(228), 1,
      sym__hexdigit,
  [741] = 1,
    ACTIONS(230), 1,
      sym__hexdigit,
  [745] = 1,
    ACTIONS(232), 1,
      sym__hexdigit,
  [749] = 1,
    ACTIONS(234), 1,
      sym__hexdigit,
  [753] = 1,
    ACTIONS(236), 1,
      sym__hexdigit,
  [757] = 1,
    ACTIONS(238), 1,
      sym__hexdigit,
  [761] = 1,
    ACTIONS(240), 1,
      sym__hexdigit,
  [765] = 1,
    ACTIONS(242), 1,
      anon_sym_LF,
  [769] = 1,
    ACTIONS(244), 1,
      sym__identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 44,
  [SMALL_STATE(4)] = 88,
  [SMALL_STATE(5)] = 112,
  [SMALL_STATE(6)] = 136,
  [SMALL_STATE(7)] = 156,
  [SMALL_STATE(8)] = 176,
  [SMALL_STATE(9)] = 192,
  [SMALL_STATE(10)] = 212,
  [SMALL_STATE(11)] = 228,
  [SMALL_STATE(12)] = 244,
  [SMALL_STATE(13)] = 262,
  [SMALL_STATE(14)] = 278,
  [SMALL_STATE(15)] = 292,
  [SMALL_STATE(16)] = 316,
  [SMALL_STATE(17)] = 340,
  [SMALL_STATE(18)] = 358,
  [SMALL_STATE(19)] = 372,
  [SMALL_STATE(20)] = 385,
  [SMALL_STATE(21)] = 398,
  [SMALL_STATE(22)] = 421,
  [SMALL_STATE(23)] = 434,
  [SMALL_STATE(24)] = 455,
  [SMALL_STATE(25)] = 468,
  [SMALL_STATE(26)] = 481,
  [SMALL_STATE(27)] = 502,
  [SMALL_STATE(28)] = 523,
  [SMALL_STATE(29)] = 536,
  [SMALL_STATE(30)] = 557,
  [SMALL_STATE(31)] = 578,
  [SMALL_STATE(32)] = 587,
  [SMALL_STATE(33)] = 596,
  [SMALL_STATE(34)] = 605,
  [SMALL_STATE(35)] = 619,
  [SMALL_STATE(36)] = 633,
  [SMALL_STATE(37)] = 639,
  [SMALL_STATE(38)] = 649,
  [SMALL_STATE(39)] = 656,
  [SMALL_STATE(40)] = 663,
  [SMALL_STATE(41)] = 670,
  [SMALL_STATE(42)] = 675,
  [SMALL_STATE(43)] = 680,
  [SMALL_STATE(44)] = 685,
  [SMALL_STATE(45)] = 692,
  [SMALL_STATE(46)] = 697,
  [SMALL_STATE(47)] = 701,
  [SMALL_STATE(48)] = 705,
  [SMALL_STATE(49)] = 709,
  [SMALL_STATE(50)] = 713,
  [SMALL_STATE(51)] = 717,
  [SMALL_STATE(52)] = 721,
  [SMALL_STATE(53)] = 725,
  [SMALL_STATE(54)] = 729,
  [SMALL_STATE(55)] = 733,
  [SMALL_STATE(56)] = 737,
  [SMALL_STATE(57)] = 741,
  [SMALL_STATE(58)] = 745,
  [SMALL_STATE(59)] = 749,
  [SMALL_STATE(60)] = 753,
  [SMALL_STATE(61)] = 757,
  [SMALL_STATE(62)] = 761,
  [SMALL_STATE(63)] = 765,
  [SMALL_STATE(64)] = 769,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_value, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_message_value, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_value, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_message_value, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_placeable, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_placeable, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_message_value_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_message_value_repeat1, 2, 0, 0),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_message_value_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_placeable, 4, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_placeable, 4, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_placeable, 5, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_placeable, 5, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blank_lines, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_blank_lines, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_blank_lines_repeat1, 2, 0, 0),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_blank_lines_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_blank_lines_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_continuation, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_message_continuation, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_comment, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file_comment, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group_comment, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group_comment, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_with_comment, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_message_with_comment, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_message, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 4, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_message, 4, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 5, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_message, 5, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quoted_text_repeat1, 2, 0, 0),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_text_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_text_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_text_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_text_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_escaped, 1, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_escaped, 5, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_escaped, 7, 0, 0),
  [181] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_message_with_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_message_with_comment_repeat1, 2, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_text, 3, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_text, 2, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 2, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [212] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_fluent(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "fluent",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
