/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 79
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 58
#define ALIAS_COUNT 5
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 7
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 13
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment_content = 1,
  anon_sym_POUND = 2,
  anon_sym_POUND_POUND = 3,
  anon_sym_POUND_POUND_POUND = 4,
  aux_sym_message_token1 = 5,
  anon_sym_EQ = 6,
  anon_sym_DOT = 7,
  sym_identifier = 8,
  anon_sym_DASH = 9,
  anon_sym_DOLLAR = 10,
  aux_sym_selector_variant_token1 = 11,
  aux_sym_selector_variant_token2 = 12,
  aux_sym_selectors_token1 = 13,
  anon_sym_RBRACE = 14,
  aux_sym_placeable_token1 = 15,
  aux_sym_placeable_token2 = 16,
  sym_number = 17,
  anon_sym_DQUOTE = 18,
  aux_sym_quoted_text_token1 = 19,
  anon_sym_BSLASHu = 20,
  anon_sym_BSLASHU = 21,
  anon_sym_BSLASH_DQUOTE = 22,
  anon_sym_BSLASH_BSLASH = 23,
  sym__hexdigit = 24,
  sym_pattern_start = 25,
  sym_pattern_pure_text = 26,
  sym_pattern_end = 27,
  sym_pattern_skip = 28,
  sym_blank_lines = 29,
  sym_unfinished_line = 30,
  sym_close_comment_block = 31,
  sym_source = 32,
  sym__base_comment = 33,
  sym__comment_block = 34,
  sym_comment_block = 35,
  sym_group_comment = 36,
  sym_file_comment = 37,
  sym_with_doc_comment = 38,
  sym_message = 39,
  sym_attribute = 40,
  sym_term = 41,
  sym_term_identifier = 42,
  sym_variable = 43,
  sym_pattern = 44,
  sym_expression = 45,
  sym_selector_key = 46,
  sym_selector_variant = 47,
  sym_selectors = 48,
  sym_placeable = 49,
  sym_quoted_text = 50,
  sym_quoted_escaped = 51,
  aux_sym_source_repeat1 = 52,
  aux_sym__comment_block_repeat1 = 53,
  aux_sym_message_repeat1 = 54,
  aux_sym_pattern_repeat1 = 55,
  aux_sym_selectors_repeat1 = 56,
  aux_sym_quoted_text_repeat1 = 57,
  alias_sym_attributes = 58,
  alias_sym_content = 59,
  anon_alias_sym_identifier = 60,
  alias_sym_message_id = 61,
  alias_sym_term_id = 62,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment_content] = "comment_content",
  [anon_sym_POUND] = "# ",
  [anon_sym_POUND_POUND] = "## ",
  [anon_sym_POUND_POUND_POUND] = "### ",
  [aux_sym_message_token1] = "message_token1",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT] = ".",
  [sym_identifier] = "identifier",
  [anon_sym_DASH] = "-",
  [anon_sym_DOLLAR] = "$",
  [aux_sym_selector_variant_token1] = "selector_variant_token1",
  [aux_sym_selector_variant_token2] = "selector_variant_token2",
  [aux_sym_selectors_token1] = "selectors_token1",
  [anon_sym_RBRACE] = "}",
  [aux_sym_placeable_token1] = "placeable_token1",
  [aux_sym_placeable_token2] = "placeable_token2",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_text_token1] = "quoted_text_token1",
  [anon_sym_BSLASHu] = "\\u",
  [anon_sym_BSLASHU] = "\\U",
  [anon_sym_BSLASH_DQUOTE] = "\\\"",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [sym__hexdigit] = "_hexdigit",
  [sym_pattern_start] = "pattern_start",
  [sym_pattern_pure_text] = "pattern_pure_text",
  [sym_pattern_end] = "pattern_end",
  [sym_pattern_skip] = "pattern_skip",
  [sym_blank_lines] = "blank_lines",
  [sym_unfinished_line] = "unfinished_line",
  [sym_close_comment_block] = "close_comment_block",
  [sym_source] = "source",
  [sym__base_comment] = "_base_comment",
  [sym__comment_block] = "_comment_block",
  [sym_comment_block] = "comment_block",
  [sym_group_comment] = "group_comment",
  [sym_file_comment] = "file_comment",
  [sym_with_doc_comment] = "with_doc_comment",
  [sym_message] = "message",
  [sym_attribute] = "attribute",
  [sym_term] = "term",
  [sym_term_identifier] = "term_identifier",
  [sym_variable] = "variable",
  [sym_pattern] = "pattern",
  [sym_expression] = "expression",
  [sym_selector_key] = "selector_key",
  [sym_selector_variant] = "selector_variant",
  [sym_selectors] = "selectors",
  [sym_placeable] = "placeable",
  [sym_quoted_text] = "quoted_text",
  [sym_quoted_escaped] = "quoted_escaped",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym__comment_block_repeat1] = "_comment_block_repeat1",
  [aux_sym_message_repeat1] = "message_repeat1",
  [aux_sym_pattern_repeat1] = "pattern_repeat1",
  [aux_sym_selectors_repeat1] = "selectors_repeat1",
  [aux_sym_quoted_text_repeat1] = "quoted_text_repeat1",
  [alias_sym_attributes] = "attributes",
  [alias_sym_content] = "content",
  [anon_alias_sym_identifier] = "identifier",
  [alias_sym_message_id] = "message_id",
  [alias_sym_term_id] = "term_id",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment_content] = sym_comment_content,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_POUND_POUND] = anon_sym_POUND_POUND,
  [anon_sym_POUND_POUND_POUND] = anon_sym_POUND_POUND_POUND,
  [aux_sym_message_token1] = aux_sym_message_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_identifier] = sym_identifier,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [aux_sym_selector_variant_token1] = aux_sym_selector_variant_token1,
  [aux_sym_selector_variant_token2] = aux_sym_selector_variant_token2,
  [aux_sym_selectors_token1] = aux_sym_selectors_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_placeable_token1] = aux_sym_placeable_token1,
  [aux_sym_placeable_token2] = aux_sym_placeable_token2,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_text_token1] = aux_sym_quoted_text_token1,
  [anon_sym_BSLASHu] = anon_sym_BSLASHu,
  [anon_sym_BSLASHU] = anon_sym_BSLASHU,
  [anon_sym_BSLASH_DQUOTE] = anon_sym_BSLASH_DQUOTE,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [sym__hexdigit] = sym__hexdigit,
  [sym_pattern_start] = sym_pattern_start,
  [sym_pattern_pure_text] = sym_pattern_pure_text,
  [sym_pattern_end] = sym_pattern_end,
  [sym_pattern_skip] = sym_pattern_skip,
  [sym_blank_lines] = sym_blank_lines,
  [sym_unfinished_line] = sym_unfinished_line,
  [sym_close_comment_block] = sym_close_comment_block,
  [sym_source] = sym_source,
  [sym__base_comment] = sym__base_comment,
  [sym__comment_block] = sym__comment_block,
  [sym_comment_block] = sym_comment_block,
  [sym_group_comment] = sym_group_comment,
  [sym_file_comment] = sym_file_comment,
  [sym_with_doc_comment] = sym_with_doc_comment,
  [sym_message] = sym_message,
  [sym_attribute] = sym_attribute,
  [sym_term] = sym_term,
  [sym_term_identifier] = sym_term_identifier,
  [sym_variable] = sym_variable,
  [sym_pattern] = sym_pattern,
  [sym_expression] = sym_expression,
  [sym_selector_key] = sym_selector_key,
  [sym_selector_variant] = sym_selector_variant,
  [sym_selectors] = sym_selectors,
  [sym_placeable] = sym_placeable,
  [sym_quoted_text] = sym_quoted_text,
  [sym_quoted_escaped] = sym_quoted_escaped,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym__comment_block_repeat1] = aux_sym__comment_block_repeat1,
  [aux_sym_message_repeat1] = aux_sym_message_repeat1,
  [aux_sym_pattern_repeat1] = aux_sym_pattern_repeat1,
  [aux_sym_selectors_repeat1] = aux_sym_selectors_repeat1,
  [aux_sym_quoted_text_repeat1] = aux_sym_quoted_text_repeat1,
  [alias_sym_attributes] = alias_sym_attributes,
  [alias_sym_content] = alias_sym_content,
  [anon_alias_sym_identifier] = anon_alias_sym_identifier,
  [alias_sym_message_id] = alias_sym_message_id,
  [alias_sym_term_id] = alias_sym_term_id,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_message_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_selector_variant_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_selector_variant_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_selectors_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_placeable_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_placeable_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_text_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASHu] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHU] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [sym__hexdigit] = {
    .visible = false,
    .named = true,
  },
  [sym_pattern_start] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern_pure_text] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern_end] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern_skip] = {
    .visible = true,
    .named = true,
  },
  [sym_blank_lines] = {
    .visible = true,
    .named = true,
  },
  [sym_unfinished_line] = {
    .visible = true,
    .named = true,
  },
  [sym_close_comment_block] = {
    .visible = true,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__base_comment] = {
    .visible = false,
    .named = true,
  },
  [sym__comment_block] = {
    .visible = false,
    .named = true,
  },
  [sym_comment_block] = {
    .visible = true,
    .named = true,
  },
  [sym_group_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_file_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_with_doc_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_message] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_term_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_selector_key] = {
    .visible = true,
    .named = true,
  },
  [sym_selector_variant] = {
    .visible = true,
    .named = true,
  },
  [sym_selectors] = {
    .visible = true,
    .named = true,
  },
  [sym_placeable] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_text] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_escaped] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__comment_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_message_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_selectors_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_text_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_attributes] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_content] = {
    .visible = true,
    .named = true,
  },
  [anon_alias_sym_identifier] = {
    .visible = true,
    .named = false,
  },
  [alias_sym_message_id] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_term_id] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_attributes = 1,
  field_id = 2,
  field_key = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_attributes] = "attributes",
  [field_id] = "id",
  [field_key] = "key",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [4] = {.index = 0, .length = 1},
  [5] = {.index = 1, .length = 2},
  [6] = {.index = 3, .length = 2},
  [7] = {.index = 5, .length = 3},
  [10] = {.index = 8, .length = 1},
  [11] = {.index = 9, .length = 2},
  [12] = {.index = 11, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_id, 0},
  [1] =
    {field_id, 0},
    {field_value, 3},
  [3] =
    {field_attributes, 4},
    {field_id, 0},
  [5] =
    {field_attributes, 4},
    {field_id, 0},
    {field_value, 3},
  [8] =
    {field_id, 1},
  [9] =
    {field_id, 1},
    {field_value, 4},
  [11] =
    {field_key, 1},
    {field_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_content,
  },
  [2] = {
    [1] = anon_alias_sym_identifier,
  },
  [3] = {
    [0] = sym_comment_block,
  },
  [6] = {
    [4] = alias_sym_attributes,
  },
  [7] = {
    [4] = alias_sym_attributes,
  },
  [8] = {
    [0] = alias_sym_message_id,
  },
  [9] = {
    [0] = alias_sym_term_id,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__comment_block, 2,
    sym__comment_block,
    sym_comment_block,
  sym_term_identifier, 2,
    sym_term_identifier,
    alias_sym_term_id,
  aux_sym_message_repeat1, 2,
    aux_sym_message_repeat1,
    alias_sym_attributes,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 29,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 31,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 9,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(aux_sym_message_token1);
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '\n', 12,
        ' ', 23,
        '"', 40,
        '#', 5,
        '$', 31,
        '*', 11,
        '-', 30,
        '.', 27,
        '[', 32,
        '\\', 9,
        ']', 33,
        '{', 36,
        '}', 35,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(28);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(34);
      if (lookahead == ' ') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == ' ') ADVANCE(2);
      if (lookahead == '-') ADVANCE(10);
      if (lookahead == '}') ADVANCE(37);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == ' ') ADVANCE(2);
      if (lookahead == '-') ADVANCE(10);
      if (lookahead == '}') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(46);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(20);
      if (lookahead == '#') ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(21);
      if (lookahead == '#') ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(22);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 9:
      if (lookahead == '"') ADVANCE(44);
      if (lookahead == 'U') ADVANCE(43);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead == 'u') ADVANCE(42);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(1);
      END_STATE();
    case 11:
      if (lookahead == '[') ADVANCE(32);
      END_STATE();
    case 12:
      if (lookahead == ']') ADVANCE(33);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\n' ||
          lookahead == ' ') ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == ']') ADVANCE(33);
      if (lookahead == '\n' ||
          lookahead == ' ') ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\n' ||
          lookahead == ' ') ADVANCE(14);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 16:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 17:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '"', 40,
        '#', 5,
        '$', 31,
        '*', 11,
        '-', 29,
        '.', 27,
        '=', 26,
        '[', 32,
        ']', 33,
        '{', 36,
        '}', 35,
        '\n', 13,
        ' ', 13,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_comment_content);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_POUND_POUND);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_message_token1);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == ' ') ADVANCE(23);
      if (lookahead == '-') ADVANCE(10);
      if (lookahead == ']') ADVANCE(33);
      if (lookahead == '}') ADVANCE(37);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_message_token1);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == ' ') ADVANCE(24);
      if (lookahead == '-') ADVANCE(10);
      if (lookahead == '}') ADVANCE(37);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_message_token1);
      if (lookahead == ' ') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(1);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_selector_variant_token1);
      if (lookahead == '\n' ||
          lookahead == ' ') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_selector_variant_token2);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_selectors_token1);
      if (lookahead == '\n' ||
          lookahead == ' ') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_placeable_token1);
      if (lookahead == '\n' ||
          lookahead == ' ') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_placeable_token2);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_quoted_text_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_BSLASHu);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_BSLASHU);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_BSLASH_DQUOTE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__hexdigit);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 17, .external_lex_state = 2},
  [2] = {.lex_state = 17, .external_lex_state = 2},
  [3] = {.lex_state = 17, .external_lex_state = 2},
  [4] = {.lex_state = 17, .external_lex_state = 2},
  [5] = {.lex_state = 17, .external_lex_state = 2},
  [6] = {.lex_state = 17, .external_lex_state = 2},
  [7] = {.lex_state = 17, .external_lex_state = 2},
  [8] = {.lex_state = 17, .external_lex_state = 2},
  [9] = {.lex_state = 17, .external_lex_state = 2},
  [10] = {.lex_state = 17, .external_lex_state = 2},
  [11] = {.lex_state = 17},
  [12] = {.lex_state = 17, .external_lex_state = 2},
  [13] = {.lex_state = 17, .external_lex_state = 2},
  [14] = {.lex_state = 17, .external_lex_state = 2},
  [15] = {.lex_state = 17, .external_lex_state = 2},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 17, .external_lex_state = 2},
  [18] = {.lex_state = 17, .external_lex_state = 2},
  [19] = {.lex_state = 8},
  [20] = {.lex_state = 8},
  [21] = {.lex_state = 17, .external_lex_state = 2},
  [22] = {.lex_state = 17, .external_lex_state = 3},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 17, .external_lex_state = 3},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 17, .external_lex_state = 3},
  [28] = {.lex_state = 17, .external_lex_state = 4},
  [29] = {.lex_state = 17, .external_lex_state = 4},
  [30] = {.lex_state = 17, .external_lex_state = 4},
  [31] = {.lex_state = 17, .external_lex_state = 5},
  [32] = {.lex_state = 17},
  [33] = {.lex_state = 17},
  [34] = {.lex_state = 17, .external_lex_state = 3},
  [35] = {.lex_state = 17, .external_lex_state = 5},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 17},
  [38] = {.lex_state = 17, .external_lex_state = 4},
  [39] = {.lex_state = 0, .external_lex_state = 6},
  [40] = {.lex_state = 17},
  [41] = {.lex_state = 24},
  [42] = {.lex_state = 17, .external_lex_state = 4},
  [43] = {.lex_state = 0, .external_lex_state = 6},
  [44] = {.lex_state = 0, .external_lex_state = 7},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 0, .external_lex_state = 7},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 17},
  [52] = {.lex_state = 17},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 25},
  [57] = {.lex_state = 17},
  [58] = {.lex_state = 16},
  [59] = {.lex_state = 17},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 17},
  [63] = {.lex_state = 17},
  [64] = {.lex_state = 17},
  [65] = {.lex_state = 17},
  [66] = {.lex_state = 16},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 17},
  [71] = {.lex_state = 16},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 17},
  [74] = {.lex_state = 3},
  [75] = {.lex_state = 25},
  [76] = {.lex_state = 3},
  [77] = {.lex_state = 25},
  [78] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(1),
    [aux_sym_message_token1] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [aux_sym_selector_variant_token1] = ACTIONS(1),
    [aux_sym_selector_variant_token2] = ACTIONS(1),
    [aux_sym_selectors_token1] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [aux_sym_placeable_token1] = ACTIONS(1),
    [aux_sym_placeable_token2] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASHu] = ACTIONS(1),
    [anon_sym_BSLASHU] = ACTIONS(1),
    [anon_sym_BSLASH_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(1),
    [sym__hexdigit] = ACTIONS(1),
    [sym_pattern_start] = ACTIONS(1),
    [sym_pattern_pure_text] = ACTIONS(1),
    [sym_pattern_end] = ACTIONS(1),
    [sym_pattern_skip] = ACTIONS(1),
    [sym_blank_lines] = ACTIONS(1),
    [sym_unfinished_line] = ACTIONS(1),
    [sym_close_comment_block] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source] = STATE(67),
    [sym__base_comment] = STATE(27),
    [sym__comment_block] = STATE(22),
    [sym_comment_block] = STATE(2),
    [sym_group_comment] = STATE(2),
    [sym_file_comment] = STATE(2),
    [sym_with_doc_comment] = STATE(2),
    [sym_message] = STATE(2),
    [sym_term] = STATE(2),
    [sym_term_identifier] = STATE(77),
    [aux_sym_source_repeat1] = STATE(2),
    [aux_sym__comment_block_repeat1] = STATE(27),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_POUND] = ACTIONS(5),
    [anon_sym_POUND_POUND] = ACTIONS(7),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [sym_blank_lines] = ACTIONS(15),
    [sym_unfinished_line] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_POUND_POUND,
    ACTIONS(9), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(22), 1,
      sym__comment_block,
    STATE(77), 1,
      sym_term_identifier,
    ACTIONS(19), 2,
      sym_blank_lines,
      sym_unfinished_line,
    STATE(27), 2,
      sym__base_comment,
      aux_sym__comment_block_repeat1,
    STATE(3), 7,
      sym_comment_block,
      sym_group_comment,
      sym_file_comment,
      sym_with_doc_comment,
      sym_message,
      sym_term,
      aux_sym_source_repeat1,
  [42] = 11,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      anon_sym_POUND,
    ACTIONS(26), 1,
      anon_sym_POUND_POUND,
    ACTIONS(29), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(32), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_DASH,
    STATE(22), 1,
      sym__comment_block,
    STATE(77), 1,
      sym_term_identifier,
    ACTIONS(38), 2,
      sym_blank_lines,
      sym_unfinished_line,
    STATE(27), 2,
      sym__base_comment,
      aux_sym__comment_block_repeat1,
    STATE(3), 7,
      sym_comment_block,
      sym_group_comment,
      sym_file_comment,
      sym_with_doc_comment,
      sym_message,
      sym_term,
      aux_sym_source_repeat1,
  [84] = 4,
    ACTIONS(43), 1,
      anon_sym_DOT,
    STATE(8), 1,
      aux_sym_message_repeat1,
    STATE(10), 1,
      sym_attribute,
    ACTIONS(41), 8,
      sym_blank_lines,
      sym_unfinished_line,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      sym_identifier,
      anon_sym_DASH,
  [104] = 4,
    ACTIONS(43), 1,
      anon_sym_DOT,
    STATE(6), 1,
      aux_sym_message_repeat1,
    STATE(10), 1,
      sym_attribute,
    ACTIONS(45), 8,
      sym_blank_lines,
      sym_unfinished_line,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      sym_identifier,
      anon_sym_DASH,
  [124] = 4,
    ACTIONS(43), 1,
      anon_sym_DOT,
    STATE(8), 1,
      aux_sym_message_repeat1,
    STATE(10), 1,
      sym_attribute,
    ACTIONS(47), 8,
      sym_blank_lines,
      sym_unfinished_line,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      sym_identifier,
      anon_sym_DASH,
  [144] = 4,
    ACTIONS(43), 1,
      anon_sym_DOT,
    STATE(4), 1,
      aux_sym_message_repeat1,
    STATE(10), 1,
      sym_attribute,
    ACTIONS(49), 8,
      sym_blank_lines,
      sym_unfinished_line,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      sym_identifier,
      anon_sym_DASH,
  [164] = 4,
    ACTIONS(53), 1,
      anon_sym_DOT,
    STATE(8), 1,
      aux_sym_message_repeat1,
    STATE(10), 1,
      sym_attribute,
    ACTIONS(51), 8,
      sym_blank_lines,
      sym_unfinished_line,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      sym_identifier,
      anon_sym_DASH,
  [184] = 1,
    ACTIONS(56), 9,
      sym_blank_lines,
      sym_unfinished_line,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_DOT,
      sym_identifier,
      anon_sym_DASH,
  [196] = 1,
    ACTIONS(58), 9,
      sym_blank_lines,
      sym_unfinished_line,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_DOT,
      sym_identifier,
      anon_sym_DASH,
  [208] = 8,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(60), 1,
      sym_identifier,
    ACTIONS(62), 1,
      anon_sym_DOLLAR,
    ACTIONS(64), 1,
      sym_number,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    STATE(36), 1,
      sym_expression,
    STATE(50), 1,
      sym_term_identifier,
    STATE(48), 2,
      sym_variable,
      sym_quoted_text,
  [234] = 1,
    ACTIONS(68), 9,
      sym_blank_lines,
      sym_unfinished_line,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_DOT,
      sym_identifier,
      anon_sym_DASH,
  [246] = 1,
    ACTIONS(70), 9,
      sym_blank_lines,
      sym_unfinished_line,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_DOT,
      sym_identifier,
      anon_sym_DASH,
  [258] = 1,
    ACTIONS(72), 8,
      sym_blank_lines,
      sym_unfinished_line,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      sym_identifier,
      anon_sym_DASH,
  [269] = 1,
    ACTIONS(74), 8,
      sym_blank_lines,
      sym_unfinished_line,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      sym_identifier,
      anon_sym_DASH,
  [280] = 6,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    ACTIONS(78), 1,
      aux_sym_quoted_text_token1,
    ACTIONS(80), 1,
      anon_sym_BSLASHu,
    ACTIONS(82), 1,
      anon_sym_BSLASHU,
    ACTIONS(84), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(19), 2,
      sym_quoted_escaped,
      aux_sym_quoted_text_repeat1,
  [301] = 1,
    ACTIONS(86), 8,
      sym_blank_lines,
      sym_unfinished_line,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      sym_identifier,
      anon_sym_DASH,
  [312] = 1,
    ACTIONS(88), 8,
      sym_blank_lines,
      sym_unfinished_line,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      sym_identifier,
      anon_sym_DASH,
  [323] = 6,
    ACTIONS(80), 1,
      anon_sym_BSLASHu,
    ACTIONS(82), 1,
      anon_sym_BSLASHU,
    ACTIONS(90), 1,
      anon_sym_DQUOTE,
    ACTIONS(92), 1,
      aux_sym_quoted_text_token1,
    ACTIONS(84), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(20), 2,
      sym_quoted_escaped,
      aux_sym_quoted_text_repeat1,
  [344] = 6,
    ACTIONS(94), 1,
      anon_sym_DQUOTE,
    ACTIONS(96), 1,
      aux_sym_quoted_text_token1,
    ACTIONS(99), 1,
      anon_sym_BSLASHu,
    ACTIONS(102), 1,
      anon_sym_BSLASHU,
    ACTIONS(105), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(20), 2,
      sym_quoted_escaped,
      aux_sym_quoted_text_repeat1,
  [365] = 1,
    ACTIONS(108), 8,
      sym_blank_lines,
      sym_unfinished_line,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      sym_identifier,
      anon_sym_DASH,
  [376] = 5,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(110), 1,
      sym_close_comment_block,
    STATE(77), 1,
      sym_term_identifier,
    STATE(14), 2,
      sym_message,
      sym_term,
  [393] = 1,
    ACTIONS(112), 6,
      anon_sym_DQUOTE,
      aux_sym_quoted_text_token1,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
  [402] = 3,
    ACTIONS(114), 1,
      anon_sym_POUND,
    STATE(24), 2,
      sym__base_comment,
      aux_sym__comment_block_repeat1,
    ACTIONS(117), 3,
      sym_close_comment_block,
      sym_identifier,
      anon_sym_DASH,
  [415] = 1,
    ACTIONS(119), 6,
      anon_sym_DQUOTE,
      aux_sym_quoted_text_token1,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
  [424] = 1,
    ACTIONS(121), 6,
      anon_sym_DQUOTE,
      aux_sym_quoted_text_token1,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
  [433] = 3,
    ACTIONS(5), 1,
      anon_sym_POUND,
    STATE(24), 2,
      sym__base_comment,
      aux_sym__comment_block_repeat1,
    ACTIONS(123), 3,
      sym_close_comment_block,
      sym_identifier,
      anon_sym_DASH,
  [446] = 4,
    ACTIONS(125), 1,
      aux_sym_placeable_token1,
    ACTIONS(128), 1,
      sym_pattern_pure_text,
    ACTIONS(131), 1,
      sym_pattern_end,
    STATE(28), 2,
      sym_placeable,
      aux_sym_pattern_repeat1,
  [460] = 4,
    ACTIONS(133), 1,
      aux_sym_placeable_token1,
    ACTIONS(135), 1,
      sym_pattern_pure_text,
    ACTIONS(137), 1,
      sym_pattern_end,
    STATE(28), 2,
      sym_placeable,
      aux_sym_pattern_repeat1,
  [474] = 4,
    ACTIONS(133), 1,
      aux_sym_placeable_token1,
    ACTIONS(135), 1,
      sym_pattern_pure_text,
    ACTIONS(139), 1,
      sym_pattern_end,
    STATE(28), 2,
      sym_placeable,
      aux_sym_pattern_repeat1,
  [488] = 3,
    ACTIONS(133), 1,
      aux_sym_placeable_token1,
    ACTIONS(141), 1,
      sym_pattern_pure_text,
    STATE(29), 2,
      sym_placeable,
      aux_sym_pattern_repeat1,
  [499] = 3,
    ACTIONS(143), 1,
      aux_sym_selector_variant_token1,
    ACTIONS(146), 1,
      anon_sym_RBRACE,
    STATE(32), 2,
      sym_selector_variant,
      aux_sym_selectors_repeat1,
  [510] = 3,
    ACTIONS(148), 1,
      aux_sym_selector_variant_token1,
    ACTIONS(150), 1,
      anon_sym_RBRACE,
    STATE(32), 2,
      sym_selector_variant,
      aux_sym_selectors_repeat1,
  [521] = 1,
    ACTIONS(152), 4,
      sym_close_comment_block,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_DASH,
  [528] = 3,
    ACTIONS(133), 1,
      aux_sym_placeable_token1,
    ACTIONS(154), 1,
      sym_pattern_pure_text,
    STATE(30), 2,
      sym_placeable,
      aux_sym_pattern_repeat1,
  [539] = 3,
    ACTIONS(156), 1,
      aux_sym_selectors_token1,
    ACTIONS(158), 1,
      aux_sym_placeable_token2,
    STATE(38), 1,
      sym_selectors,
  [549] = 2,
    ACTIONS(148), 1,
      aux_sym_selector_variant_token1,
    STATE(33), 2,
      sym_selector_variant,
      aux_sym_selectors_repeat1,
  [557] = 1,
    ACTIONS(160), 3,
      sym_pattern_pure_text,
      sym_pattern_end,
      aux_sym_placeable_token1,
  [563] = 3,
    ACTIONS(162), 1,
      sym_pattern_start,
    ACTIONS(164), 1,
      sym_pattern_skip,
    STATE(5), 1,
      sym_pattern,
  [573] = 2,
    STATE(63), 1,
      sym_selector_key,
    ACTIONS(166), 2,
      sym_identifier,
      sym_number,
  [581] = 2,
    ACTIONS(168), 1,
      aux_sym_message_token1,
    ACTIONS(170), 2,
      aux_sym_selectors_token1,
      aux_sym_placeable_token2,
  [589] = 1,
    ACTIONS(172), 3,
      sym_pattern_pure_text,
      sym_pattern_end,
      aux_sym_placeable_token1,
  [595] = 3,
    ACTIONS(162), 1,
      sym_pattern_start,
    ACTIONS(174), 1,
      sym_pattern_skip,
    STATE(13), 1,
      sym_pattern,
  [605] = 2,
    ACTIONS(176), 1,
      sym_pattern_start,
    STATE(51), 1,
      sym_pattern,
  [612] = 1,
    ACTIONS(178), 2,
      aux_sym_selectors_token1,
      aux_sym_placeable_token2,
  [617] = 1,
    ACTIONS(180), 2,
      aux_sym_selectors_token1,
      aux_sym_placeable_token2,
  [622] = 1,
    ACTIONS(182), 2,
      aux_sym_selectors_token1,
      aux_sym_placeable_token2,
  [627] = 1,
    ACTIONS(184), 2,
      aux_sym_selectors_token1,
      aux_sym_placeable_token2,
  [632] = 2,
    ACTIONS(162), 1,
      sym_pattern_start,
    STATE(18), 1,
      sym_pattern,
  [639] = 1,
    ACTIONS(186), 2,
      aux_sym_selectors_token1,
      aux_sym_placeable_token2,
  [644] = 1,
    ACTIONS(188), 2,
      aux_sym_selector_variant_token1,
      anon_sym_RBRACE,
  [649] = 1,
    ACTIONS(56), 2,
      aux_sym_selector_variant_token1,
      anon_sym_RBRACE,
  [654] = 1,
    ACTIONS(190), 2,
      aux_sym_selectors_token1,
      aux_sym_placeable_token2,
  [659] = 1,
    ACTIONS(192), 1,
      sym__hexdigit,
  [663] = 1,
    ACTIONS(194), 1,
      sym__hexdigit,
  [667] = 1,
    ACTIONS(196), 1,
      aux_sym_message_token1,
  [671] = 1,
    ACTIONS(198), 1,
      sym_identifier,
  [675] = 1,
    ACTIONS(200), 1,
      sym_comment_content,
  [679] = 1,
    ACTIONS(202), 1,
      sym_identifier,
  [683] = 1,
    ACTIONS(204), 1,
      sym__hexdigit,
  [687] = 1,
    ACTIONS(206), 1,
      sym__hexdigit,
  [691] = 1,
    ACTIONS(208), 1,
      aux_sym_selector_variant_token2,
  [695] = 1,
    ACTIONS(210), 1,
      aux_sym_selector_variant_token2,
  [699] = 1,
    ACTIONS(212), 1,
      anon_sym_EQ,
  [703] = 1,
    ACTIONS(214), 1,
      sym_identifier,
  [707] = 1,
    ACTIONS(216), 1,
      sym_comment_content,
  [711] = 1,
    ACTIONS(218), 1,
      ts_builtin_sym_end,
  [715] = 1,
    ACTIONS(220), 1,
      sym__hexdigit,
  [719] = 1,
    ACTIONS(222), 1,
      sym__hexdigit,
  [723] = 1,
    ACTIONS(224), 1,
      anon_sym_EQ,
  [727] = 1,
    ACTIONS(226), 1,
      sym_comment_content,
  [731] = 1,
    ACTIONS(228), 1,
      sym__hexdigit,
  [735] = 1,
    ACTIONS(230), 1,
      anon_sym_EQ,
  [739] = 1,
    ACTIONS(232), 1,
      sym__hexdigit,
  [743] = 1,
    ACTIONS(234), 1,
      aux_sym_message_token1,
  [747] = 1,
    ACTIONS(236), 1,
      sym__hexdigit,
  [751] = 1,
    ACTIONS(238), 1,
      aux_sym_message_token1,
  [755] = 1,
    ACTIONS(240), 1,
      sym__hexdigit,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 42,
  [SMALL_STATE(4)] = 84,
  [SMALL_STATE(5)] = 104,
  [SMALL_STATE(6)] = 124,
  [SMALL_STATE(7)] = 144,
  [SMALL_STATE(8)] = 164,
  [SMALL_STATE(9)] = 184,
  [SMALL_STATE(10)] = 196,
  [SMALL_STATE(11)] = 208,
  [SMALL_STATE(12)] = 234,
  [SMALL_STATE(13)] = 246,
  [SMALL_STATE(14)] = 258,
  [SMALL_STATE(15)] = 269,
  [SMALL_STATE(16)] = 280,
  [SMALL_STATE(17)] = 301,
  [SMALL_STATE(18)] = 312,
  [SMALL_STATE(19)] = 323,
  [SMALL_STATE(20)] = 344,
  [SMALL_STATE(21)] = 365,
  [SMALL_STATE(22)] = 376,
  [SMALL_STATE(23)] = 393,
  [SMALL_STATE(24)] = 402,
  [SMALL_STATE(25)] = 415,
  [SMALL_STATE(26)] = 424,
  [SMALL_STATE(27)] = 433,
  [SMALL_STATE(28)] = 446,
  [SMALL_STATE(29)] = 460,
  [SMALL_STATE(30)] = 474,
  [SMALL_STATE(31)] = 488,
  [SMALL_STATE(32)] = 499,
  [SMALL_STATE(33)] = 510,
  [SMALL_STATE(34)] = 521,
  [SMALL_STATE(35)] = 528,
  [SMALL_STATE(36)] = 539,
  [SMALL_STATE(37)] = 549,
  [SMALL_STATE(38)] = 557,
  [SMALL_STATE(39)] = 563,
  [SMALL_STATE(40)] = 573,
  [SMALL_STATE(41)] = 581,
  [SMALL_STATE(42)] = 589,
  [SMALL_STATE(43)] = 595,
  [SMALL_STATE(44)] = 605,
  [SMALL_STATE(45)] = 612,
  [SMALL_STATE(46)] = 617,
  [SMALL_STATE(47)] = 622,
  [SMALL_STATE(48)] = 627,
  [SMALL_STATE(49)] = 632,
  [SMALL_STATE(50)] = 639,
  [SMALL_STATE(51)] = 644,
  [SMALL_STATE(52)] = 649,
  [SMALL_STATE(53)] = 654,
  [SMALL_STATE(54)] = 659,
  [SMALL_STATE(55)] = 663,
  [SMALL_STATE(56)] = 667,
  [SMALL_STATE(57)] = 671,
  [SMALL_STATE(58)] = 675,
  [SMALL_STATE(59)] = 679,
  [SMALL_STATE(60)] = 683,
  [SMALL_STATE(61)] = 687,
  [SMALL_STATE(62)] = 691,
  [SMALL_STATE(63)] = 695,
  [SMALL_STATE(64)] = 699,
  [SMALL_STATE(65)] = 703,
  [SMALL_STATE(66)] = 707,
  [SMALL_STATE(67)] = 711,
  [SMALL_STATE(68)] = 715,
  [SMALL_STATE(69)] = 719,
  [SMALL_STATE(70)] = 723,
  [SMALL_STATE(71)] = 727,
  [SMALL_STATE(72)] = 731,
  [SMALL_STATE(73)] = 735,
  [SMALL_STATE(74)] = 739,
  [SMALL_STATE(75)] = 743,
  [SMALL_STATE(76)] = 747,
  [SMALL_STATE(77)] = 751,
  [SMALL_STATE(78)] = 755,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 5, 0, 6),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 4, 0, 5),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 5, 0, 7),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 4, 0, 4),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_message_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_message_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_message_repeat1, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 5, 0, 10),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 5, 0, 11),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_with_doc_comment, 2, 0, 3),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_comment, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_block, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 4, 0, 5),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quoted_text_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_text_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_text_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_text_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_text_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group_comment, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_escaped, 1, 0, 0),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__comment_block_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__comment_block_repeat1, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_escaped, 7, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_escaped, 5, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment_block, 1, 0, 0),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_selectors_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_selectors_repeat1, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__base_comment, 2, 0, 1),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_placeable, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_identifier, 2, 0, 2),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_identifier, 2, 0, 2),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selectors, 3, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2, 0, 2),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_text, 3, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 8),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 9),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector_variant, 4, 0, 12),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_text, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector_key, 1, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [218] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_pattern_start = 0,
  ts_external_token_pattern_pure_text = 1,
  ts_external_token_pattern_end = 2,
  ts_external_token_pattern_skip = 3,
  ts_external_token_blank_lines = 4,
  ts_external_token_unfinished_line = 5,
  ts_external_token_close_comment_block = 6,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_pattern_start] = sym_pattern_start,
  [ts_external_token_pattern_pure_text] = sym_pattern_pure_text,
  [ts_external_token_pattern_end] = sym_pattern_end,
  [ts_external_token_pattern_skip] = sym_pattern_skip,
  [ts_external_token_blank_lines] = sym_blank_lines,
  [ts_external_token_unfinished_line] = sym_unfinished_line,
  [ts_external_token_close_comment_block] = sym_close_comment_block,
};

static const bool ts_external_scanner_states[8][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_pattern_start] = true,
    [ts_external_token_pattern_pure_text] = true,
    [ts_external_token_pattern_end] = true,
    [ts_external_token_pattern_skip] = true,
    [ts_external_token_blank_lines] = true,
    [ts_external_token_unfinished_line] = true,
    [ts_external_token_close_comment_block] = true,
  },
  [2] = {
    [ts_external_token_blank_lines] = true,
    [ts_external_token_unfinished_line] = true,
  },
  [3] = {
    [ts_external_token_close_comment_block] = true,
  },
  [4] = {
    [ts_external_token_pattern_pure_text] = true,
    [ts_external_token_pattern_end] = true,
  },
  [5] = {
    [ts_external_token_pattern_pure_text] = true,
  },
  [6] = {
    [ts_external_token_pattern_start] = true,
    [ts_external_token_pattern_skip] = true,
  },
  [7] = {
    [ts_external_token_pattern_start] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_fluent_external_scanner_create(void);
void tree_sitter_fluent_external_scanner_destroy(void *);
bool tree_sitter_fluent_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_fluent_external_scanner_serialize(void *, char *);
void tree_sitter_fluent_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_fluent(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_fluent_external_scanner_create,
      tree_sitter_fluent_external_scanner_destroy,
      tree_sitter_fluent_external_scanner_scan,
      tree_sitter_fluent_external_scanner_serialize,
      tree_sitter_fluent_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "fluent",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 2,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
